const CUSTOMER_SITES = {
    // 普通影视源
    dyttzy: { api: 'http://caiji.dyttzyapi.com/api.php/provide/vod', name: '🎬电影天堂' },
    heimuer: { api: 'https://json.heimuer.xyz/api.php/provide/vod', name: '🎬黑木耳' },
    ruyi: { api: 'http://cj.rycjapi.com/api.php/provide/vod', name: '🎬如意资源' },
    bfzy: { api: 'https://bfzyapi.com/api.php/provide/vod', name: '🎬暴风资源' },
    tyyszy: { api: 'https://tyyszy.com/api.php/provide/vod', name: '🎬天涯资源' },
    ffzy: { api: 'http://ffzy5.tv/api.php/provide/vod', name: '🎬非凡影视' },
    zy360: { api: 'https://360zy.com/api.php/provide/vod', name: '🎬360资源' },
    maotaizy: { api: 'https://caiji.maotaizy.cc/api.php/provide/vod', name: '🎬茅台资源' },
    wolong: { api: 'https://wolongzyw.com/api.php/provide/vod', name: '🎬卧龙资源' },
    jisu: { api: 'https://jszyapi.com/api.php/provide/vod', name: '🎬极速资源' },
    dbzy: { api: 'https://dbzy.tv/api.php/provide/vod', name: '🎬豆瓣资源' },
    mozhua: { api: 'https://mozhuazy.com/api.php/provide/vod', name: '🎬魔爪资源' },
    mdzy: { api: 'https://www.mdzyapi.com/api.php/provide/vod', name: '🎬魔都资源' },
    zuid: { api: 'https://api.zuidapi.com/api.php/provide/vod', name: '🎬最大资源' },
    yinghua: { api: 'https://m3u8.apiyhzy.com/api.php/provide/vod', name: '🎬樱花资源' },
    wujin: { api: 'https://api.wujinapi.me/api.php/provide/vod', name: '🎬无尽资源' },
    wwzy: { api: 'https://wwzy.tv/api.php/provide/vod', name: '🎬旺旺短剧' },
    ikun: { api: 'https://ikunzyapi.com/api.php/provide/vod', name: '🎬iKun资源' },
    lzi: { api: 'https://cj.lziapi.com/api.php/provide/vod', name: '🎬量子资源' },
    xiaomaomi: { api: 'https://zy.xmm.hk/api.php/provide/vod', name: '🎬小猫咪资源' },
    iqiyizy: { api: 'https://iqiyizyapi.com/api.php/provide/vod', name: '🎬爱奇艺资源' },
    dbzy5: { api: 'https://caiji.dbzy5.com/api.php/provide/vod', name: '🎬豆瓣资源2' },
    ikunzy: { api: 'https://ikunzyapi.com/api.php/provide/vod', name: '🎬iKun资源2' },
    maoyan: { api: 'https://api.maoyanapi.top/api.php/provide/vod', name: '🎬猫眼资源' },
    lzcaiji: { api: 'https://cj.lzcaiji.com/api.php/provide/vod', name: '🎬量子资源2' },
    zy360v2: { api: 'https://360zyzz.com/api.php/provide/vod', name: '🎬360资源2' },
    ffzyv2: { api: 'https://api.ffzyapi.com/api.php/provide/vod', name: '🎬非凡资源2' },
    wujinv2: { api: 'https://api.wujinapi.me/api.php/provide/vod', name: '🎬无尽资源2' },
    xinlang: { api: 'https://api.xinlangapi.com/xinlangapi.php/provide/vod', name: '🎬新浪资源' },
    wwzyv2: { api: 'https://api.wwzy.tv/api.php/provide/vod', name: '🎬旺旺资源2' },
    subo: { api: 'https://subocaiji.com/api.php/provide/vod', name: '🎬速播资源' },
    jinying: { api: 'https://jinyingzy.com/api.php/provide/vod', name: '🎬金鹰点播' },
    piaoliao: { api: 'https://p2100.net/api.php/provide/vod', name: '🎬飘零资源' },
    uku: { api: 'https://api.ukuapi88.com/api.php/provide/vod', name: '🎬U酷影视' },
    guangsu: { api: 'https://api.guangsuapi.com/api.php/provide/vod', name: '🎬光速资源' },
    hongniu: { api: 'https://www.hongniuzy2.com/api.php/provide/vod', name: '🎬红牛资源' },
    moduanime: { api: 'https://caiji.moduapi.cc/api.php/provide/vod', name: '🎬魔都动漫' },
    haohua: { api: 'https://pz.168188.dpdns.org/?url=https://hhzyapi.com/api.php/provide/vod', name: '🎬豪华资源' },
    baiduyun: { api: 'https://bdzy1.com/api.php/provide/vod', name: '🎬百度云zy' },
    aidan: { api: 'https://aidanzy.com/api.php/provide/vod', name: '🎬艾旦资源' },
    // 成人源
    madou: { api: 'https://caiji.madouzyapi.com/api.php/provide/vod', name: '🔞麻豆资源', adult: true },
    fanhao: { api: 'http://fhapi9.com/api.php/provide/vod', name: '🔞番号资源', adult: true },
    lsb: { api: 'https://apilsbzy1.com/api.php/provide/vod', name: '🔞老色逼', adult: true },
    youyou: { api: 'https://www.yyzywcj.com/api.php/provide/vod', name: '🔞优优资源', adult: true },
    xiaoji: { api: 'https://api.xiaojizy.live/provide/vod', name: '🔞小鸡资源', adult: true },
    huangse: { api: 'https://hsckzy.xyz/api.php/provide/vod', name: '🔞黄色仓库', adult: true },
    danai: { api: 'https://apidanaizi.com/api.php/provide/vod', name: '🔞大奶子', adult: true },
    jkun: { api: 'https://jkunzyapi.com/api.php/provide/vod', name: '🔞jkun资源', adult: true },
    lebo: { api: 'https://lbapi9.com/api.php/provide/vod', name: '🔞乐播资源', adult: true },
    slap: { api: 'https://slapibf.com/api.php/provide/vod', name: '🔞SLAP资源', adult: true },
    lajiao: { api: 'https://pz.168188.dpdns.org/?url=https://apilj.com/api.php/provide/vod', name: '🔞辣椒资源', adult: true },
    shayu: { api: 'https://shayuapi.com/api.php/provide/vod', name: '🔞鲨鱼资源', adult: true },
    xingzy: { api: 'https://xzybb2.com/api.php/provide/vod', name: '🔞幸资源', adult: true },
    doudou: { api: 'https://api.douapi.cc/api.php/provide/vod', name: '🔞豆豆资源', adult: true },
    didi: { api: 'https://api.ddapi.cc/api.php/provide/vod', name: '🔞滴滴资源', adult: true },
    heiliao: { api: 'https://www.heiliaozyapi.com/api.php/provide/vod', name: '🔞黑料资源', adult: true },
    baiwan: { api: 'https://api.bwzyz.com/api.php/provide/vod', name: '🔞百万资源', adult: true },
    taohua: { api: 'https://thzy1.me/api.php/provide/vod', name: '🔞桃花资源', adult: true },
    jingpin: { api: 'https://www.jingpinx.com/api.php/provide/vod', name: '🔞精品资源', adult: true },
    souav: { api: 'https://api.souavzyw.net/api.php/provide/vod', name: '🔞souavZY', adult: true },
};

// 调用全局方法合并
if (window.extendAPISites) {
    window.extendAPISites(CUSTOMER_SITES);
} else {
    console.error("错误：请先加载 config.js！");
}
